spring:
  application:
    name: @application.name@
  grpc:
    server:
      port: ${GRPC_PORT:9094}
      servlet:
        enabled: false
      health:
        actuator:
          enabled: false

server:
  port: ${HTTP_PORT}

app:
  grpc:
    deadline: ${GRPC_DEADLINE}
    keep-alive-time: 60000
    server:
      client:
        host: ${SERVER_GRPC_HOST}
        port: ${SERVER_GRPC_PORT}
